version: '3.8'

services:
  rebootcord-app:
    build: .
    container_name: rebootcord-main
    ports:
      - "1000:1000"
      - "25565-25864:25565-25864"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - NODE_ENV=production
      - PORT=1000
      - SESSION_SECRET=rebootcord-secret-key
      - MC_PORT_MIN=25565
      - MC_PORT_MAX=25864
    volumes:
      - ./data:/app/data
      - ./projects_data:/app/projects_data
    restart: unless-stopped
